# Generated by Django 5.2.4 on 2025-08-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",), "verbose_name_plural": "dishes"},
        ),
    ]
