# Generated by Django 5.2.4 on 2025-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_dish_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
