# Generated by Django 5.2.4 on 2025-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_dishtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
