# Generated by Django 5.2.4 on 2025-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_dish_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
